name = "hl-vs-etoro-proxy"
main = "index.js"
compatibility_date = "2024-11-01"

[vars]
ETORO_INSTRUMENT_OIL = "17"
# ETORO_INSTRUMENT_NQ = ""
# ETORO_INSTRUMENT_GOLD = ""
# ETORO_INSTRUMENT_NATGAS = ""
# ETORO_CANDLE_HOST = "https://candle.etoro.com"
