name = "hl-vs-etoro-proxy"
main = "index.js"
compatibility_date = "2024-11-01"

[vars]
ETORO_INSTRUMENT_NQ = "686"
ETORO_INSTRUMENT_GOLD = "559"
ETORO_INSTRUMENT_SILVER = "783"
ETORO_INSTRUMENT_OIL = "784"
ETORO_INSTRUMENT_NATGAS = "782"
# ETORO_CANDLE_HOST = "https://candle.etoro.com"
